backend:
  name: github
  repo: sezardino/Gatsby-edu
  branch: netlify-cms

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /uploads
show_preview_links: true

collections:
  - name: blog
    label: Blog
    folder: /src/content/blog
    create: true
    slug: post-{{title}}
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - file: src/content/pages/home.md
        label: "Home"
        name: "home"
        fields:
          - { name: title, label: Title, widget: hidden, default: Home }
          - { name: navOrder, label: Order in menu, widget: hidden, default: 1 }
          - { name: name, label: Name, widget: string }
          - { name: surname, label: Surname, widget: string }
          - { name: position, label: Position, widget: string }
          - { name: image, label: Image, widget: image }
      - file: src/content/pages/about.md
        label: "About"
        name: "about"
        fields:
          - { name: title, label: Title, widget: hidden, default: About }
          - { name: navOrder, label: Order in menu, widget: hidden, default: 2 }
          - { name: sTitle, label: Page Title, widget: string }
          - { name: frstText, label: First paragraph, widget: string }
          - { name: scndText, label: Second paragraph, widget: string }
      - file: src/content/pages/widgets.md
        label: "Test widgets"
        name: "test"
        fields:
          - { name: title, label: Title, widget: string, default: About }
          - { name: boolean, label: Boolean, widget: boolean, required: true, default: false}
          - { name: code, label: Code, widget: code}
          - { name: color, label: Color, widget: color, allowInput: true, enableAlpha: true }
          - { name: date, label: Date, widget: date, format: 'MMM Do YY' }
          - { name: dateTime, label: DateTime, widget: datetime}
          - { name: file, label: File, widget: file, required: false }
